name: applying
on: 
  workflow_dispatch:
    inputs:
      action:
        description: 'creating newrelic'
        required: true
        default: 'apply'
        options:
          - 'apply'
          - 'apply'
env:
  BUCKET: workflow-bucket-synthetic-monitor
  TFSTATE_FILE: terraform.tfstate
  aws_region: us-east-1
#   pull_request:
#     branches:
#       - main
  # push:
  #   branches:
  #     - main
  
 
        
jobs:
  Test-monitor:
    runs-on : ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{ env.aws_region }}
      - name: Initialize Terraform
        run: terraform init
        working-directory: Test-monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test-monitor

      - name: Initialize Terraform
        run: terraform init
        working-directory: Test2-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test2-Monitor

      - name: Initialize Terraform
        run: terraform init
        working-directory: Test3-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test3-Monitor  

      - name: Initialize Terraform
        run: terraform init
        working-directory: Test4-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test4-Monitor

      - name: Initialize Terraform
        run: terraform init
        working-directory: Test5-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test5-Monitor

      
      - name: Initialize Terraform
        run: terraform init
        working-directory: Test6-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test6-Monitor

      - name: Initialize Terraform
        run: terraform init
        working-directory: Test7-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test7-Monitor

        - name: Initialize Terraform
        run: terraform init
        working-directory: Test8-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test8-Monitor

      - name: Initialize Terraform
        run: terraform init
        working-directory: Test9-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test9-Monitor

      - name: Initialize Terraform
        run: terraform init
        working-directory: Test10-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test10-Monitor

      - name: Initialize Terraform
        run: terraform init
        working-directory: Test11-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test11-Monitor

      - name: Initialize Terraform
        run: terraform init
        working-directory: Test12-Monitor

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: Test12-Monitor


       



